sudo: false
language: cpp
osx_image: xcode11 # at least until travis default osx version works
jobs:
    include:
        - os: linux
          compiler: gcc
        - os: linux
          compiler: clang
        - os: linux
          compiler: clang
          arch: arm64
        - os: osx
          compiler: clang
script:
  - cmake . && cmake --build .
  - cd ..
  - git clone https://github.com/ghewgill/neon-lang
  - ln -s ../../neon-hash neon-lang/lib/hash
  - cd neon-lang
  - cmake . && cmake --build .
  - ctest -R hash
