sudo: false
language: cpp
osx_image: xcode11 # at least until travis default osx version works
jobs:
    include:
        - os: linux
          compiler: gcc
        - os: linux
          compiler: clang
        - os: linux
          compiler: clang
          arch: arm64
        - os: osx
          compiler: clang
script:
  - cmake . && cmake --build .
